# make use of vm's
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
before_install:
  - './.travis/main.sh'
  
script:
  - './.travis/build-docker.sh'
