sudo: false

language: node_js

node_js:
  - "iojs"
  - "7"

install: 
  - npm install -g typescript

  - npm install -g typings

  - npm install 

# Final script that starts the testing.
script: npm test
