#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

rootDir=$(pwd)

if  git status | grep 'backend/' &> /dev/null
then
    cd backend
    npm run lint
fi

if  git status | grep 'frontend/' &> /dev/null
then
    cd "$rootDir/frontend"
    npm run lint
fi
